#!/bin/bash

if [ "$1" == "" ]
then
   echo "Usage: $0 <splashfile>.img"
   exit
fi

INPUT=$1
FILENOEXT=${INPUT%.*}

SIZE=$(nbsize -f $INPUT)
echo "Resolution: $SIZE"
command=$(ffmpeg -loglevel panic -f rawvideo -pix_fmt rgb565 -s $SIZE -i $INPUT -f image2 $FILENOEXT.png)
