#!/bin/bash

if [ "$1" == "" ]
then
    echo "Usage: $0 <splashfile>.png [outfile]"
    exit
fi

INPUT=$1
FILENOEXT=${INPUT%.*}

if [ ! "$2" == "" ]
then
   TEMP=$2
   FILENOEXT=${TEMP%.*}
fi

ffmpeg -loglevel panic -i $INPUT -f rawvideo -pix_fmt rgb565 $FILENOEXT.img
